options(download.file.method="libcurl")
library(lubridate)
library(rbokeh)
library(forecast)
library(tseries)

data = read.csv("macro.csv", header=FALSE)
name_1 = "Макроэкономика"
name_2 = "Макроэкономика прогноз"
macro <- ts(data[,2], freq=365.25/7, start=decimal_date(ymd("2012-11-04")))
fit <- tbats(macro)
plot(fit, main = name_1)
dev.copy(png, paste0(name_1,'.png'))
dev.off()
summary(fit)
fc <- forecast(fit, h=53)
plot(fc, main = name_2)
dev.copy(png,paste0(name_2,'.png'))
dev.off()
plot(fit$errors)
adf.test(fit$errors)
Box.test(fit$errors, lag = 1, type = c("Box-Pierce", "Ljung-Box"), fitdf = 0)

data = read.csv("micro.csv", header=FALSE)
name_1 = "Микроэкономика"
name_2 = "Микроэкономика прогноз"
micro <- ts(data[,2], freq=365.25/7, start=decimal_date(ymd("2012-11-04")))
fit <- tbats(micro) 
plot(fit, main = name_1)
dev.copy(png, paste0(name_1,'.png'))
dev.off()
summary(fit)
fc <- forecast(fit, h=53)
plot(fc, main = name_2)
dev.copy(png,paste0(name_2,'.png'))
dev.off()
plot(fit$errors)
adf.test(fit$errors)
Box.test(fit$errors, lag = 1, type = c("Box-Pierce", "Ljung-Box"), fitdf = 0)

data = read.csv("econometrics.csv", header=FALSE)
name_1 = "Эконометрика"
name_2 = "Эконометрика прогноз"
econometrics <- ts(data[,2], freq=365.25/7, start=decimal_date(ymd("2012-11-04")))
fit <- tbats(econometrics) 
plot(fit, main = name_1)
dev.copy(png, paste0(name_1,'.png'))
dev.off()
summary(fit)
fc <- forecast(fit, h=53)
plot(fc, main = name_2)
dev.copy(png,paste0(name_2,'.png'))
dev.off()
plot(fit$errors)
adf.test(fit$errors)
Box.test(fit$errors, lag = 1, type = c("Box-Pierce", "Ljung-Box"), fitdf = 0)

data = read.csv("instek.csv", header=FALSE)
name_1 = "Инстэк"
name_2 = "Инстэк прогноз"
instek <- ts(data[,2], freq=365.25/7, start=decimal_date(ymd("2012-11-04")))
fit <- tbats(instek) 
plot(fit, main = name_1)
dev.copy(png, paste0(name_1,'.png'))
dev.off()
summary(fit)
fc <- forecast(fit, h=53)
plot(fc, main = name_2)
dev.copy(png,paste0(name_2,'.png'))
dev.off()
plot(fit$errors)
adf.test(fit$errors)
Box.test(fit$errors, lag = 1, type = c("Box-Pierce", "Ljung-Box"), fitdf = 0)

data = read.csv("altai.csv", header=FALSE)
name_1 = "Алтайский государственный университет"
name_2 = "Алтайский государственный университет прогноз"
altai <- ts(data[,2], freq=365.25/7, start=decimal_date(ymd("2012-11-04")))
fit <- tbats(altai)
plot(fit, main = name_1)
dev.copy(png, paste0(name_1,'.png'))
dev.off()
summary(fit)
fc <- forecast(fit, h=53)
plot(fc, main = name_2)
dev.copy(png,paste0(name_2,'.png'))
dev.off()
plot(fit$errors)
adf.test(fit$errors)
Box.test(fit$errors, lag = 1, type = c("Box-Pierce", "Ljung-Box"), fitdf = 0)

data = read.csv("belgorod.csv", header=FALSE)
name_1 = "Белгородский государственный университет"
name_2 = "Белгородский государственный университет прогноз"
belgorod <- ts(data[,2], freq=365.25/7, start=decimal_date(ymd("2012-11-04")))
fit <- tbats(belgorod) 
plot(fit, main = name_1)
dev.copy(png, paste0(name_1,'.png'))
dev.off()
summary(fit)
fc <- forecast(fit, h=53)
plot(fc, main = name_2)
dev.copy(png,paste0(name_2,'.png'))
dev.off()
plot(fit$errors)
adf.test(fit$errors)
Box.test(fit$errors, lag = 1, type = c("Box-Pierce", "Ljung-Box"), fitdf = 0)

data = read.csv("ranepa.csv", header=FALSE)
name_1 = "РАНХиГС"
name_2 = "РАНХиГС прогноз"
ranepa <- ts(data[,2], freq=365.25/7, start=decimal_date(ymd("2012-11-04")))
fit <- tbats(ranepa) 
plot(fit, main = name_1)
dev.copy(png, paste0(name_1,'.png'))
dev.off()
summary(fit)
fc <- forecast(fit, h=53)
plot(fc, main = name_2)
dev.copy(png,paste0(name_2,'.png'))
dev.off()
plot(fit$errors)
adf.test(fit$errors)
Box.test(fit$errors, lag = 1, type = c("Box-Pierce", "Ljung-Box"), fitdf = 0)

data = read.csv("voronezh.csv", header=FALSE)
name_1 = "Воронежский государственный университет"
name_2 = "Воронежский государственный университет прогноз"
voronezh <- ts(data[,2], freq=365.25/7, start=decimal_date(ymd("2012-11-04")))
fit <- tbats(voronezh) 
plot(fit, main = name_1)
dev.copy(png, paste0(name_1,'.png'))
dev.off()
summary(fit)
fc <- forecast(fit, h=53)
plot(fc, main = name_2)
dev.copy(png,paste0(name_2,'.png'))
dev.off()
plot(fit$errors)
adf.test(fit$errors)
Box.test(fit$errors, lag = 1, type = c("Box-Pierce", "Ljung-Box"), fitdf = 0)

data = read.csv("kemerovo.csv", header=FALSE)
name_1 = "Кемеровский государственный университет"
name_2 = "Кемеровский государственный университет прогноз"
kemer <- ts(data[,2], freq=365.25/7, start=decimal_date(ymd("2012-11-04")))
fit <- tbats(kemer) 
plot(fit, main = name_1)
dev.copy(png, paste0(name_1,'.png'))
dev.off()
summary(fit)
fc <- forecast(fit, h=53)
plot(fc, main = name_2)
dev.copy(png,paste0(name_2,'.png'))
dev.off()
plot(fit$errors)
adf.test(fit$errors)
Box.test(fit$errors, lag = 1, type = c("Box-Pierce", "Ljung-Box"), fitdf = 0)


data = read.csv("yale.csv", header=FALSE)
name_1 = "Yale university"
name_2 = "Yale university прогноз"
yale <- ts(data[,2], freq=365.25/7, start=decimal_date(ymd("2012-11-04")))
fit <- tbats(yale) 
plot(fit, main = name_1)
dev.copy(png, paste0(name_1,'.png'))
dev.off()
summary(fit)
fc <- forecast(fit, h=53)
plot(fc, main = name_2)
dev.copy(png,paste0(name_2,'.png'))
dev.off()
plot(fit$errors) 
adf.test(fit$errors) 
Box.test(fit$errors, lag = 1, type = c("Box-Pierce", "Ljung-Box"), fitdf = 0)

data = read.csv("caltech.csv", header=FALSE)
name_1 = "Caltech"
name_2 = "Caltech прогноз"
caltech <- ts(data[,2], freq=365.25/7, start=decimal_date(ymd("2012-11-04")))
fit <- tbats(caltech) 
plot(fit, main = name_1)
dev.copy(png, paste0(name_1,'.png'))
dev.off()
summary(fit)
fit$alpha
fc <- forecast(fit, h=53)
plot(fc, main = name_2)
dev.copy(png,paste0(name_2,'.png'))
dev.off()
plot(fit$errors)
adf.test(fit$errors)
Box.test(fit$errors, lag = 1, type = c("Box-Pierce", "Ljung-Box"), fitdf = 0)

data = read.csv("princeton.csv", header=FALSE)
name_1 = "University of Princeton"
name_2 = "University of Princeton прогноз"
prince <- ts(data[,2], freq=365.25/7, start=decimal_date(ymd("2012-11-04")))
fit <- tbats(prince) 
plot(fit, main = name_1)
dev.copy(png, paste0(name_1,'.png'))
dev.off()
summary(fit)
fit$alpha
fc <- forecast(fit, h=53)
plot(fc, main = name_2)
dev.copy(png,paste0(name_2,'.png'))
dev.off()
plot(fit$errors)
adf.test(fit$errors)
Box.test(fit$errors, lag = 1, type = c("Box-Pierce", "Ljung-Box"), fitdf = 0)

data = read.csv("jhu.csv", header=FALSE)
name_1 = "John Hopkins university"
name_2 = "John Hopkins university прогноз"
jhu <- ts(data[,2], freq=365.25/7, start=decimal_date(ymd("2012-11-04")))
fit <- tbats(jhu) 
plot(fit, main = name_1)
dev.copy(png, paste0(name_1,'.png'))
dev.off()
summary(fit)
fc <- forecast(fit, h=53)
plot(fc, main = name_2)
dev.copy(png,paste0(name_2,'.png'))
dev.off()
plot(fit$errors)
adf.test(fit$errors)
Box.test(fit$errors, lag = 1, type = c("Box-Pierce", "Ljung-Box"), fitdf = 0)

data = read.csv("nusingapore.csv", header=FALSE)
name_1 = "National University of Singapore"
name_2 = "National University of Singapore прогноз"
nsu <- ts(data[,2], freq=365.25/7, start=decimal_date(ymd("2012-11-04")))
fit <- tbats(nsu) 
plot(fit, main = name_1)
dev.copy(png, paste0(name_1,'.png'))
dev.off()
summary(fit)
fc <- forecast(fit, h=53)
plot(fc, main = name_2)
dev.copy(png,paste0(name_2,'.png'))
dev.off()
plot(fit$errors)
adf.test(fit$errors)
Box.test(fit$errors, lag = 1, type = c("Box-Pierce", "Ljung-Box"), fitdf = 0)



